# Generated by Django 4.2.2 on 2023-06-21 18:40

from django.db import migrations
import json
from pathlib import Path


def load_articles(apps, schema_editor):
    Article = apps.get_model("news", "Article")
    BASE_DIR = Path(__file__).resolve().parent.parent.parent
    with open(BASE_DIR / "static/articles.json", "r", encoding="utf-8") as file:
        articles = json.load(file)
        for article_data in articles:
            Article.objects.create(
                title=article_data["title"],
                body=article_data["body"],
                access_path=article_data.get("access_path"),
            )


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_article_picture"),
    ]

    operations = [
        migrations.RunPython(load_articles),
    ]
